#!/bin/bash

usage()
{
    echo "Usage: make_chroot_initrd [-o initrd.chroot] current_initrd"
    echo "  Make new initrd image supporting chroot= boot parameter from existing image."
    echo "  New image is written to 'current_initrd.chroot' unless -o is specified (no need to run as root then)."
    echo "  Supported Systems: debian, ubuntu and derivatives."
    exit 1
}

die() { echo -e "make_chroot_initrd: $@"; exit 1; }

out=""
if [ "$1" = "-o" ]; then
    shift; out="$1"; shift
fi

# create temp dir
cwd=`pwd`
tmp="/tmp/make_chroot_initrd"
rm -rf "$tmp" 2>/dev/null
mkdir $tmp || die "can't create dir $tmp"

# check input file
initrd="$1"
[ -f "$initrd" ] || usage
file "$initrd" | grep -q 'gzip compressed data' || die "expecting a gzipped initrd"
[ -z "$out" ] && out="${initrd}.chroot"

# script home dir
[ -f "$cwd/make_chroot_initrd" ]         && script_dir="$cwd"
[ -f "$script_dir/initrd.patch" ] || die "initrd.patch is missing"

echo "making new initrd: $out"
cp "$initrd" "$tmp/initrd.gz"
cd $tmp || die "can't access $tmp"

echo "extracting"
gunzip initrd.gz			|| die "gunzip failed"
mkdir tmp; cd tmp
cpio --quiet -i < ../initrd		|| die "cpio failed"

echo "patching"
patch --silent --dry-run -p1 < "$script_dir/initrd.patch" >/dev/null && \
patch --silent -p1 < "$script_dir/initrd.patch"	|| \
patch --silent -p1 < "$script_dir/initrd_1604.patch" || die "patch failed !"
rm *.orig */*.orig 2>/dev/null

echo "packing"
find . | cpio --quiet -o --format='newc' > ../initrd
cd ..
gzip initrd

cd "$cwd"				|| die "cd $cwd failed"
cp $tmp/initrd.gz "$out"		|| die "now run \n    sudo cp $tmp/initrd.gz $out"
rm -rf $tmp
echo "done !"
